### ISSUE TITLE
License file is using a template note

### ISSUE THREAD

**Issue by hybridherbst** [Unity-Technologies/unity-inverse-dynamics-demo#1]
Seems https://github.com/Unity-Technologies/unity-inverse-dynamics-demo/blob/main/LICENSE.md is still using a template line:
```
Please make sure that the link to the Unity Companion License is actually working correctly after committing--this is CRITICAL.
```

I guess that should be removed.

**Comment by JuozasK** [comment]
haha, yeah good point! Removed
